// Enc-Dec key for login creds: Key=3pl678

export const convertCamelSnakeCase = (string) => {
  // Convert snake_case to spaces
  let result = string.replace(/_/g, ' ');

  // Convert camelCase to spaces
  result = result.replace(/([a-z])([A-Z])/g, '$1 $2');

  // Convert to uppercase
  result = result.toUpperCase();

  return result;
}

export const jsonData = {
  payoutDate: "20.01.24",
  amount: 810.00,
  seller: "TalhaKShop",
  previous: "-",
  lastSequence: 318,
  net: 810.00,
  items: [
    {
      no: 136,
      date: "13.01.24",
      cod: 100,
      shipperRef: "FW212",
      description: "sandwich pan",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Pending",
      mode: "3PL",
      charges: 0,
      itemRate: 0,
      amt: 0,
      Cod: 100,
      netPayable: 100,
    },
    {
      no: 137,
      date: "14.01.24",
      cod: 150,
      shipperRef: "FW213",
      description: "kitchen knife",
      pcs: 2,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "Courier",
      charges: 10,
      itemRate: 70,
      amt: 0,
      Cod: 100,
      netPayable: 150,
    },
    {
      no: 138,
      date: "15.01.24",
      cod: 200,
      shipperRef: "FW214",
      description: "coffee maker",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "3PL",
      charges: 15,
      itemRate: 185,
      amt: 0,
      Cod: 100,
      netPayable: 200,
    },
    {
      no: 139,
      date: "16.01.24",
      cod: 360,
      shipperRef: "FW215",
      description: "blender",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "Courier",
      charges: 20,
      itemRate: 340,
      amt: 15,
      Cod: 100,
      netPayable: 360,
    },
    {
      no: 140,
      date: "17.01.24",
      cod: 120,
      shipperRef: "FW216",
      description: "toaster",
      pcs: 2,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "3PL",
      charges: 10,
      itemRate: 50,
      amt: 0,
      Cod: 100,
      netPayable: 120,
    },
    {
      no: 141,
      date: "18.01.24",
      cod: 180,
      shipperRef: "FW217",
      description: "microwave",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Pending",
      mode: "Courier",
      charges: 20,
      itemRate: 160,
      amt: 15,
      Cod: 100,
      netPayable: 180,
    },
    {
      no: 142,
      date: "19.01.24",
      cod: 210,
      shipperRef: "FW218",
      description: "blender",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "3PL",
      charges: 15,
      itemRate: 195,
      amt: 0,
      Cod: 100,
      netPayable: 210,
    },
    {
      no: 143,
      date: "20.01.24",
      cod: 95,
      shipperRef: "FW219",
      description: "spatula set",
      pcs: 3,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "Courier",
      charges: 5,
      itemRate: 30,
      amt: 0,
      Cod: 100,
      netPayable: 95,
    },
    {
      no: 144,
      date: "21.01.24",
      cod: 250,
      shipperRef: "FW220",
      description: "air fryer",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "3PL",
      charges: 20,
      itemRate: 230,
      amt: 15,
      Cod: 100,
      netPayable: 250,
    },
    {
      no: 145,
      date: "22.01.24",
      cod: 175,
      shipperRef: "FW221",
      description: "blender",
      pcs: 2,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "Courier",
      charges: 10,
      itemRate: 80,
      amt: 0,
      Cod: 100,
      netPayable: 175,
    },
    {
      no: 146,
      date: "23.01.24",
      cod: 230,
      shipperRef: "FW222",
      description: "coffee grinder",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Pending",
      mode: "3PL",
      charges: 15,
      itemRate: 215,
      amt: 0,
      Cod: 100,
      netPayable: 230,
    },
    {
      no: 147,
      date: "24.01.24",
      cod: 310,
      shipperRef: "FW223",
      description: "rice cooker",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "Courier",
      charges: 20,
      itemRate: 290,
      amt: 0,
      Cod: 100,
      netPayable: 310,
    },
    {
      no: 148,
      date: "25.01.24",
      cod: 140,
      shipperRef: "FW224",
      description: "slow cooker",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "3PL",
      charges: 10,
      itemRate: 130,
      amt: 0,
      Cod: 100,
      netPayable: 140,
    },
    {
      no: 149,
      date: "26.01.24",
      cod: 190,
      shipperRef: "FW225",
      description: "food processor",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Pending",
      mode: "Courier",
      charges: 15,
      itemRate: 175,
      amt: 0,
      Cod: 100,
      netPayable: 190,
    },
    {
      no: 150,
      date: "27.01.24",
      cod: 280,
      shipperRef: "FW226",
      description: "pressure cooker",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "3PL",
      charges: 20,
      itemRate: 260,
      amt: 0,
      Cod: 100,
      netPayable: 280,
    },
    {
      no: 151,
      date: "28.01.24",
      cod: 320,
      shipperRef: "FW227",
      description: "hand mixer",
      pcs: 2,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "Courier",
      charges: 20,
      itemRate: 300,
      amt: 0,
      Cod: 100,
      netPayable: 320,
    },
    {
      no: 152,
      date: "29.01.24",
      cod: 110,
      shipperRef: "FW228",
      description: "juicer",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Pending",
      mode: "3PL",
      charges: 10,
      itemRate: 100,
      amt: 0,
      Cod: 100,
      netPayable: 110,
    },
    {
      no: 153,
      date: "30.01.24",
      cod: 240,
      shipperRef: "FW229",
      description: "blender",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Delivered",
      mode: "Courier",
      charges: 15,
      itemRate: 225,
      amt: 0,
      Cod: 100,
      netPayable: 240,
    },
    {
      no: 154,
      date: "31.01.24",
      cod: 195,
      shipperRef: "FW230",
      description: "ice cream maker",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Shipped",
      mode: "3PL",
      charges: 10,
      itemRate: 185,
      amt: 0,
      Cod: 100,
      netPayable: 195,
    },
    {
      no: 155,
      date: "01.02.24",
      cod: 205,
      shipperRef: "FW231",
      description: "grill",
      pcs: 1,
      accountName: "TalhaKShop",
      status: "Pending",
      mode: "Courier",
      charges: 20,
      itemRate: 185,
      amt: 0,
      Cod: 100,
      netPayable: 205,
    },
  ],
  netPayable: 810,
  netBalance: 810,
};